# ===============================
# Application
# ===============================
spring.application.name=panhoramix-backend

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/panhoramix
spring.datasource.username=panhoramix
spring.datasource.password=panhoramix
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# Server
# ===============================
server.port=8080

jwt.secret=PanHorAMixSuperSecretKey2026VerySecureKey123456789
jwt.expiration=86400000

cloudflare.r2.account-id=dc496671dac81e17cdcacc8ec94f732a
cloudflare.r2.access-key=${CLOUDFLARE_ACCESS_KEY}
cloudflare.r2.secret-key=${CLOUDFLARE_SECRET_KEY}
cloudflare.r2.public-url=https://pub-7b4852df69404d88a97e53114b24e757.r2.dev
cloudflare.r2.bucket=panhoramix-media
cloudflare.r2.region=auto

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# Resend SMTP
spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
spring.mail.password=${RESEND_API_KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=${MAIL_FROM:director@panhoramix.com}
app.email-verification.secret=${EMAIL_VERIFICATION_SECRET}
