# ===============================
# Application
# ===============================
spring.application.name=panhoramix-backend

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/panhoramix
spring.datasource.username=panhoramix
spring.datasource.password=panhoramix
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# Server
# ===============================
server.port=8080

jwt.secret=PanHorAMixSuperSecretKey2026VerySecureKey123456789
jwt.expiration=86400000

cloudflare.r2.account-id=dc496671dac81e17cdcacc8ec94f732a
cloudflare.r2.access-key=${CLOUDFLARE_ACCESS_KEY}
cloudflare.r2.secret-key=${CLOUDFLARE_SECRET_KEY}
cloudflare.r2.bucket=panhoramix-media
cloudflare.r2.region=auto
